### ISSUE TITLE
macos cyfs-browser info.html diy-ood 内存信息错误

### ISSUE THREAD

**Issue by yangjunying** [buckyos/cyfs-browser#1]
macos cyfs-browser info.html diy-ood 内存信息错误。系统内存显示占比信息错误，显示为100%内存使用，实际内存使用只有60%。

**Comment by glen0125** [comment]
Many versions have been updated and this issue should have been resolved by now. Need to be tested and verified.

**Comment by Xiongdan007** [comment]
Cyfs browser windows107&mac99 version test passed
