### ISSUE TITLE
After the installation is complete, it cannot be opened directly. (Windows)

### ISSUE THREAD

**Issue by glen0125** [buckyos/cyfs-browser#10]
After the installation is complete on Windows, it cannot be opened directly. It is recommended to add a check box to the current installation completion page. After checking and clicking Finish, open the browser directly.

**Comment by ck98734** [comment]
Add radio button for select launch browser when finish install.

**Comment by ck98734** [comment]
202acb5da949bccf24bf348199b97d16dc102044

**Comment by Xiongdan007** [comment]
cyfs-browser version 113 has optional autostart
