### ISSUE TITLE
When uninstalling, it is asked multiple times whether to delete data.(Windows)

### ISSUE THREAD

**Issue by glen0125** [buckyos/cyfs-browser#11]
When uninstalling on WIndows, the user will be asked multiple times whether to delete the data, causing confusion. It is recommended to ask only once, and delete browser data and CYFS Runtime data after agreeing.

**Comment by ck98734** [comment]
Optimize the uninstallation steps

**Comment by ck98734** [comment]
202acb5da949bccf24bf348199b97d16dc102044

**Comment by Xiongdan007** [comment]
cyfs browser version 113 has modified the uninstall prompt
