### ISSUE TITLE
Long loading time of the home page after starting the browser

### ISSUE THREAD

**Issue by glen0125** [buckyos/cyfs-browser#12]
The home page is an https webpage, and the loading time depends on the network speed and resource size. Is there a better solution?

**Comment by glen0125** [comment]
A good practice is to integrate this page within the browser, without relying on external resources. However, this involves some permission issues for the page, such as the inability to initiate network requests for internal browser pages.

**Comment by ck98734** [comment]
integrate this page which have all visible element within the browser，and use iframe page Handle network requests，the host page and iframe page communicate through  postMessage method.

**Comment by ck98734** [comment]
202acb5da949bccf24bf348199b97d16dc102044

**Comment by Xiongdan007** [comment]
The home page has been changed to chrome://cyfs-init/ in win116&mac110.
