### ISSUE TITLE
The background page of the CyberChat extension has a lot of repeated error logs

### ISSUE THREAD

**Issue by glen0125** [buckyos/cyfs-browser#14]
[error], from unknown zone, Err(err: (262, post object must be handled by handler! req=9cfBkPtDymtuJu474Ez9b5vN1ELuD6ujRwC29Cz9WaVy, source: protocol=http-bdt, zone=(CurrentZone-Some(5hLXAcQTmgLbYziZwD5qYJ3CuyAMe1BQGLNUNvgd96N7)-Some(5r4MYfFRTFPDBjePAkBncmCsEAb6i2o1EhbrqcgcvipN)), dec=9tGpLNna8UVtPYCfV1LbRN2Bqa5G9vRBKhDhZiWjd7wA, verified=Some(9tGpLNna8UVtPYCfV1LbRN2Bqa5G9vRBKhDhZiWjd7wA), device=5hLXD7CSf9jVqRMZ8zfn53GsJYE4TMpLjxu48uFRuFv8, undefined))

**Comment by jinquantianxia** [comment]
IM entry of CyberChat extension is closed, problem solved.

**Comment by Xiongdan007** [comment]
cyfs browser version windows113&mac107 test passed
