### ISSUE TITLE
After the browser is installed, it will automatically open the metamask page

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#16]
Use the windows107 version to overwrite the 104 version browser or the mac99 version to overwrite the 96 version
After opening the browser page, the metamask page will be opened automatically, see the attachment for details.
expected outcome:
When the browser is opened, the page does not automatically open the metamask page
Version:
win107
mac99

**Comment by glen0125** [comment]
This is the default behavior of Metamask and we do not impose any restrictions.
