### ISSUE TITLE
When uninstalling the browser, choose not to delete the browsing data, and after installing it again, the cyberchat plug-in shows that ood is offline

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#17]
When uninstalling the browser, choose to delete runtime, not delete browsing data, and delete user information. After installing the browser again and opening the cyberchat plug-in, it shows that ood is not online, and prompts to connect to ood.
expected outcome:
ood online does not need to connect to ood (this ood is actually online), just need to activate the browser additionally
Version:
win107mac99

**Comment by glen0125** [comment]
Issue #11  is related to this issue, and will be resolved together.
