### ISSUE TITLE
After activating the cyfs browser and restarting it, an error is displayed on the homepage(occasionally)

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#20]
1. Activate the cyfs browser with superfeed and choose to restart
2. After restarting, the cyfs browser opens and displays the home page in anonymous mode
3. It will be automatically updated to the http home page later
expected outcome:
After restarting, the cyfs browser opens and shows that https has been activated on the home page
version: win107
![339729ee412be19239b6893a3c1967eb](https://user-images.githubusercontent.com/52781572/232992187-0d96c458-3792-40cf-a8f9-c4f4cc1b2299.png)

**Comment by glen0125** [comment]
This issue no longer exists as it has been resolved with the fix for #12 . The page over HTTPS is not being loaded anymore. Close it for now, but please feel free to reopen it if there are any further problems. @Xiongdan007

**Comment by Xiongdan007** [comment]
win122&mac112 test passed.
