### ISSUE TITLE
Windows version cyfs browser publisher display error

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#21]
![e77b0fb4d3677f173cb1cc4513bad9c5](https://user-images.githubusercontent.com/52781572/233539885-814770e9-4ae8-4399-b1bd-c1fc02416c6e.png)

**Comment by ck98734** [comment]
22289e124b364d94b1db1335436a8e68167ba012

**Comment by Xiongdan007** [comment]
win114 test passed.
