### ISSUE TITLE
删除首页自定义标签导致标签自我复制

### ISSUE THREAD

**Issue by yangjunying** [buckyos/cyfs-browser#3]
Cyfs Browser 1.0.0.1034 版本

1，安装Cyfs Browser 1.0.0.1034 版，安装前不删除以前的版本。
2，打开新安装的browser（cyfs://static/browser.html）页面。
3，删除一个自定义的标签。
4，发现全部的自定义标签发生了自我复制。

PS：使用sqlite数据库

**Comment by glen0125** [comment]
Many versions have been updated and this issue should have been resolved by now. Need to be tested and verified. @Xiongdan007

**Comment by Xiongdan007** [comment]
cyfs浏览器版本windows107&mac99版本测试通过
