### ISSUE TITLE
After the cyfs browser is installed, the copywriting of the browser is displayed incorrectly

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#31]
![27c049a438ac2dad0b5687c1558d956f](https://user-images.githubusercontent.com/52781572/236135544-fe69a94c-7e90-4133-ac8c-e30734bfb411.png)
version:win113
It should be displayed as shown below:
![e5a865e78e7448902ec9fd0d600b7e0b](https://user-images.githubusercontent.com/52781572/236135792-979e1297-aa1a-41c4-bb54-0496215d9145.png)

**Comment by ck98734** [comment]
22289e124b364d94b1db1335436a8e68167ba012

**Comment by Xiongdan007** [comment]
win114 test passed.
