### ISSUE TITLE
The mac&windows version of the cyfs browser has been activated and there is no user name and avatar display on the home page

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#37]
![15977254348bc3a6c0546b5720e67df4](https://user-images.githubusercontent.com/52781572/236146535-5fa069f3-0f38-41e1-a358-5aeeb60d64f3.png)
version：win113&mac107

**Comment by Xiongdan007** [comment]
![1683193076002_FA478DD9-6280-4972-8F92-B001D35AACA7](https://user-images.githubusercontent.com/52781572/236168328-568d7d4d-efb8-44fb-ac30-1463d7591c86.png)

**Comment by Xiongdan007** [comment]
win114&mac109 test failed.

**Comment by Xiongdan007** [comment]
Occasional problems require multiple tests and will not be closed for now

**Comment by ZCCCCCCCC** [comment]
Perhaps it is caused by the loading sequence, and the specific reason cannot be determined. Modifications have been made based on several possible reasons

**Comment by Xiongdan007** [comment]
win122&mac112 test passed.
