### ISSUE TITLE
Click the cyfs icon on the info page of the cyfs browser to jump to the wrong page

### ISSUE THREAD

**Issue by Xiongdan007** [buckyos/cyfs-browser#39]
![1683188452063_DE087B64-3EAA-4ffa-B24D-BBA6F7D2B83C](https://user-images.githubusercontent.com/52781572/236149171-348c03cf-f403-44df-9c1e-e296fd8d8b41.png)
Click the cyfs icon on the cyfs browser info page to jump to the page https://browser.cyfs.com/init.html
expected outcome:
Should jump to chrome://cyfs-init/
![1683188636795_BC0DF554-9657-4e2a-8DC0-6734ED0981F8](https://user-images.githubusercontent.com/52781572/236149816-fb1cb4d0-aaf4-443f-82f1-c7c0e03273f2.png)

version：win113&mac107

**Comment by ZCCCCCCCC** [comment]
Removed jump

**Comment by Xiongdan007** [comment]
win114&mac109 test passed.
