### ISSUE TITLE
Add support for ipns and ipfs

### ISSUE THREAD

**Issue by weiqiushi** [buckyos/cyfs-browser#7]
CYFS Browser can integrate IPNS and IPFS protocols like cyfs protocol: 
proxy ipns:// schema to http://localhost:38090/ipns, 
proxy ipfs:// schema to http://localhost:38090/ipfs

then cyfs-runtime can deal with them :)

**Comment by glen0125** [comment]
Already supported

**Comment by lurenpluto** [comment]
> Already supported

How is this going to work? If such support is added, it would be nice to post some design-related documentation, at least how to use it or something

**Comment by weiqiushi** [comment]
Similar to the interaction logic of cyfs-runtime, CYFS Browser will start another proxy program called " ipfs-proxy", which will listen to a local proxy port and will start kubo (https://github.com/ipfs/kubo) as the real ipfs backend

When CYFS Browser encounters the ipfs and ipns protocols, it converts them to the local proxy port started by ipfs-proxy, and this program then forwards them to the kubo backend and returns the results.
